apiVersion: apps/v1
kind: Deployment
metadata:
  name: dell
  labels:
    app: dell
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dell
  template:
    metadata:
      labels:
        app: dell
    spec:
      containers:
      - name: samplejavaapp
        image: kaushik0656m21/dell:v5
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: dell
spec:
  type: NodePort
  selector:
    app: dell
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30003
